name: Sync GitHub Wiki into repo

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true        # ← crucial

      - name: Remove existing wiki folder completely
        run: |
          rm -rf wiki

      - name: Clone wiki repository
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Sync wiki" || echo "No changes"
          git push
